from datetime import datetime, timedelta
from app.db.session import SessionLocal
from app.models.models import ProcurementCentre, CentreStatus, Slot

INDIA_MANDIS = [
    # 1. Delhi NCR
    {
        "name": "Narela Krishi Grain Mandi (APMC)",
        "code": "APC-DL-NRL-01",
        "address": "Main Bawana Road, Narela Mandi Yard, North Delhi",
        "district": "North Delhi",
        "state": "Delhi",
        "pin_code": "110040",
        "latitude": 28.8529,
        "longitude": 77.0945,
        "contact_phone": "011-27781234",
        "capacity_per_day": 250,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.0,
        "workload_pct": 68.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Najafgarh Grain Procurement Mandi (APMC)",
        "code": "APC-DL-NJF-02",
        "address": "Najafgarh Mandi Complex, Dhansa Road, South West Delhi",
        "district": "South West Delhi",
        "state": "Delhi",
        "pin_code": "110043",
        "latitude": 28.6092,
        "longitude": 76.9854,
        "contact_phone": "011-28014567",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.5,
        "workload_pct": 62.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Ghazipur Agricultural APMC Centre",
        "code": "APC-DL-GZP-03",
        "address": "Ghazipur Terminal Market, Near Anand Vihar ISBT, East Delhi",
        "district": "East Delhi",
        "state": "Delhi",
        "pin_code": "110096",
        "latitude": 28.6256,
        "longitude": 77.3325,
        "contact_phone": "011-22778899",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 8.0,
        "workload_pct": 74.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },

    # 2. Uttar Pradesh
    {
        "name": "Ghaziabad APMC Grain & Oilseed Centre",
        "code": "APC-UP-GZB-01",
        "address": "Mandi Samiti Yard, Sector 23, Govindpuram, Ghaziabad",
        "district": "Ghaziabad",
        "state": "Uttar Pradesh",
        "pin_code": "201013",
        "latitude": 28.6738,
        "longitude": 77.4984,
        "contact_phone": "0120-2789123",
        "capacity_per_day": 180,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 8.0,
        "workload_pct": 65.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Meerut Krishi Utpadan Mandi Samiti (Delhi Road)",
        "code": "APC-UP-MRT-02",
        "address": "Delhi Road Mandi Yard, Mohkampur Industrial Area, Meerut",
        "district": "Meerut",
        "state": "Uttar Pradesh",
        "pin_code": "250002",
        "latitude": 28.9482,
        "longitude": 77.6741,
        "contact_phone": "0121-2510345",
        "capacity_per_day": 160,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.5,
        "workload_pct": 58.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Bareilly Grain & Pulses APMC Mandi",
        "code": "APC-UP-BRL-03",
        "address": "Pilibhit By-Pass Road, Krishi Utpadan Mandi, Bareilly",
        "district": "Bareilly",
        "state": "Uttar Pradesh",
        "pin_code": "243006",
        "latitude": 28.3742,
        "longitude": 79.4485,
        "contact_phone": "0581-2540112",
        "capacity_per_day": 150,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 8.5,
        "workload_pct": 70.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Aligarh Anoopshahr Road Krishi Mandi",
        "code": "APC-UP-ALG-04",
        "address": "Mandi Samiti Complex, Anoopshahr Road, Aligarh",
        "district": "Aligarh",
        "state": "Uttar Pradesh",
        "pin_code": "202001",
        "latitude": 27.9152,
        "longitude": 78.0842,
        "contact_phone": "0571-2401889",
        "capacity_per_day": 140,
        "active_counters": 3,
        "total_counters": 5,
        "avg_processing_time_min": 8.0,
        "workload_pct": 55.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Agra Sikandra Regional APMC Yard",
        "code": "APC-UP-AGR-05",
        "address": "NH-19, Near Guru ka Taal, Sikandra, Agra",
        "district": "Agra",
        "state": "Uttar Pradesh",
        "pin_code": "282007",
        "latitude": 27.2185,
        "longitude": 77.9392,
        "contact_phone": "0562-2601990",
        "capacity_per_day": 170,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 8.0,
        "workload_pct": 60.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Kanpur Naubasta Central Grain APMC",
        "code": "APC-UP-KNP-06",
        "address": "Naubasta Mandi Complex, Hamirpur Road, Kanpur Nagar",
        "district": "Kanpur Nagar",
        "state": "Uttar Pradesh",
        "pin_code": "208021",
        "latitude": 26.4112,
        "longitude": 80.3241,
        "contact_phone": "0512-2612345",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.8,
        "workload_pct": 72.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Varanasi Chandpur Krishi Mandi Samiti",
        "code": "APC-UP-VNS-07",
        "address": "Industrial Estate, Chandpur, Manduadih, Varanasi",
        "district": "Varanasi",
        "state": "Uttar Pradesh",
        "pin_code": "221106",
        "latitude": 25.3082,
        "longitude": 82.9567,
        "contact_phone": "0542-2370982",
        "capacity_per_day": 160,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 8.2,
        "workload_pct": 66.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Gorakhpur Mahewa Agricultural APMC Yard",
        "code": "APC-UP-GKP-08",
        "address": "Mahewa Mandi Parisar, Transport Nagar, Gorakhpur",
        "district": "Gorakhpur",
        "state": "Uttar Pradesh",
        "pin_code": "273016",
        "latitude": 26.7412,
        "longitude": 83.3621,
        "contact_phone": "0551-2280456",
        "capacity_per_day": 180,
        "active_counters": 4,
        "total_counters": 7,
        "avg_processing_time_min": 7.9,
        "workload_pct": 69.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Mathura Krishi Utpadan Mandi (Govardhan Road)",
        "code": "APC-UP-MTH-09",
        "address": "Govardhan Chauraha, Mandi Samiti, Mathura",
        "district": "Mathura",
        "state": "Uttar Pradesh",
        "pin_code": "281004",
        "latitude": 27.5021,
        "longitude": 77.6612,
        "contact_phone": "0565-2420113",
        "capacity_per_day": 150,
        "active_counters": 3,
        "total_counters": 5,
        "avg_processing_time_min": 8.1,
        "workload_pct": 61.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Saharanpur Delhi Road Krishi Mandi",
        "code": "APC-UP-SHR-10",
        "address": "Delhi Road, Near Chunheti, Saharanpur",
        "district": "Saharanpur",
        "state": "Uttar Pradesh",
        "pin_code": "247001",
        "latitude": 29.9324,
        "longitude": 77.5412,
        "contact_phone": "0132-2760982",
        "capacity_per_day": 160,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.6,
        "workload_pct": 63.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Muzaffarnagar Kukra Krishi Mandi",
        "code": "APC-UP-MZF-11",
        "address": "Kukra Block, Mandi Samiti Campus, Muzaffarnagar",
        "district": "Muzaffarnagar",
        "state": "Uttar Pradesh",
        "pin_code": "251001",
        "latitude": 29.4782,
        "longitude": 77.7214,
        "contact_phone": "0131-2621009",
        "capacity_per_day": 170,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.4,
        "workload_pct": 60.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Jhansi Gwalior Road Krishi Mandi",
        "code": "APC-UP-JHS-12",
        "address": "Gwalior Road, Near Sipri Bazar, Jhansi",
        "district": "Jhansi",
        "state": "Uttar Pradesh",
        "pin_code": "284003",
        "latitude": 25.4612,
        "longitude": 78.5582,
        "contact_phone": "0510-2440129",
        "capacity_per_day": 140,
        "active_counters": 3,
        "total_counters": 5,
        "avg_processing_time_min": 8.0,
        "workload_pct": 57.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },

    # 3. Haryana
    {
        "name": "Karnal Central Grain APMC Mandi",
        "code": "APC-HR-KNL-01",
        "address": "GT Road, Near Sector 4, New Grain Market, Karnal",
        "district": "Karnal",
        "state": "Haryana",
        "pin_code": "132001",
        "latitude": 29.6857,
        "longitude": 76.9905,
        "contact_phone": "0184-2250123",
        "capacity_per_day": 280,
        "active_counters": 7,
        "total_counters": 10,
        "avg_processing_time_min": 6.8,
        "workload_pct": 75.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Sirsa New Anaj Mandi APMC Yard",
        "code": "APC-HR-SRS-02",
        "address": "Bhadra Road, New Anaj Mandi, Sirsa",
        "district": "Sirsa",
        "state": "Haryana",
        "pin_code": "125055",
        "latitude": 29.5342,
        "longitude": 75.0289,
        "contact_phone": "01666-231456",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.0,
        "workload_pct": 68.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Kurukshetra Pipli Grain APMC Mandi",
        "code": "APC-HR-KRK-03",
        "address": "Pipli Road, New Grain Market, Kurukshetra",
        "district": "Kurukshetra",
        "state": "Haryana",
        "pin_code": "136131",
        "latitude": 29.9812,
        "longitude": 76.8821,
        "contact_phone": "01744-230987",
        "capacity_per_day": 210,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.2,
        "workload_pct": 64.0,
        "open_time": "08:00 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Ambala City New Grain Market APMC",
        "code": "APC-HR-AMB-04",
        "address": "Near Polytechnic Chowk, New Grain Market, Ambala City",
        "district": "Ambala",
        "state": "Haryana",
        "pin_code": "134003",
        "latitude": 30.3782,
        "longitude": 76.7767,
        "contact_phone": "0171-2551234",
        "capacity_per_day": 190,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.1,
        "workload_pct": 61.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Kaithal Anaj Mandi Samiti Yard",
        "code": "APC-HR-KTL-05",
        "address": "Dhand Road, New Grain Market, Kaithal",
        "district": "Kaithal",
        "state": "Haryana",
        "pin_code": "136027",
        "latitude": 29.8015,
        "longitude": 76.4021,
        "contact_phone": "01746-224567",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.0,
        "workload_pct": 63.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Hisar New Grain & Cotton APMC Mandi",
        "code": "APC-HR-HSR-06",
        "address": "Sirsa Road, Opposite Old Courts, Hisar",
        "district": "Hisar",
        "state": "Haryana",
        "pin_code": "125001",
        "latitude": 29.1539,
        "longitude": 75.7229,
        "contact_phone": "01662-237890",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.3,
        "workload_pct": 67.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Rohtak Makrauli Grain APMC Mandi",
        "code": "APC-HR-ROH-07",
        "address": "Gohana Road, Makrauli Mandi Complex, Rohtak",
        "district": "Rohtak",
        "state": "Haryana",
        "pin_code": "124001",
        "latitude": 28.9182,
        "longitude": 76.6042,
        "contact_phone": "01262-251299",
        "capacity_per_day": 180,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.5,
        "workload_pct": 59.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Panipat Sanoli Road Grain Market",
        "code": "APC-HR-PNP-08",
        "address": "Sanoli Road, New Grain Market, Panipat",
        "district": "Panipat",
        "state": "Haryana",
        "pin_code": "132103",
        "latitude": 29.3909,
        "longitude": 76.9635,
        "contact_phone": "0180-2645112",
        "capacity_per_day": 190,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.2,
        "workload_pct": 62.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Fatehabad New Anaj Mandi Yard",
        "code": "APC-HR-FTB-09",
        "address": "Bhattu Road, New Anaj Mandi, Fatehabad",
        "district": "Fatehabad",
        "state": "Haryana",
        "pin_code": "125050",
        "latitude": 29.5132,
        "longitude": 75.4521,
        "contact_phone": "01667-220199",
        "capacity_per_day": 170,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.4,
        "workload_pct": 60.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Jind Safidon Road Grain Mandi",
        "code": "APC-HR-JND-10",
        "address": "Safidon Road, New Grain Market, Jind",
        "district": "Jind",
        "state": "Haryana",
        "pin_code": "126102",
        "latitude": 29.3142,
        "longitude": 76.3152,
        "contact_phone": "01681-252119",
        "capacity_per_day": 175,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.3,
        "workload_pct": 61.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },

    # 4. Punjab
    {
        "name": "Khanna Dana Mandi (Asia's Largest APMC Yard)",
        "code": "APC-PB-KHN-01",
        "address": "GT Road, Asia's Largest Grain Yard, Khanna",
        "district": "Ludhiana",
        "state": "Punjab",
        "pin_code": "141401",
        "latitude": 30.7071,
        "longitude": 76.2167,
        "contact_phone": "01628-226789",
        "capacity_per_day": 400,
        "active_counters": 10,
        "total_counters": 14,
        "avg_processing_time_min": 6.0,
        "workload_pct": 82.0,
        "open_time": "06:30 AM",
        "close_time": "07:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Ludhiana Dana Mandi (Gill Road)",
        "code": "APC-PB-LDH-02",
        "address": "Gill Road, Near Grain Market Flyover, Ludhiana",
        "district": "Ludhiana",
        "state": "Punjab",
        "pin_code": "141003",
        "latitude": 30.8842,
        "longitude": 75.8596,
        "contact_phone": "0161-2490123",
        "capacity_per_day": 280,
        "active_counters": 7,
        "total_counters": 10,
        "avg_processing_time_min": 6.5,
        "workload_pct": 74.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Bathinda Mansa Road Grain Market (APMC)",
        "code": "APC-PB-BTI-03",
        "address": "Mansa Road, New Grain Market, Bathinda",
        "district": "Bathinda",
        "state": "Punjab",
        "pin_code": "151001",
        "latitude": 30.2012,
        "longitude": 74.9542,
        "contact_phone": "0164-2212345",
        "capacity_per_day": 250,
        "active_counters": 6,
        "total_counters": 9,
        "avg_processing_time_min": 6.8,
        "workload_pct": 71.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Moga GT Road New Grain APMC Mandi",
        "code": "APC-PB-MOG-04",
        "address": "GT Road, New Grain Market, Moga",
        "district": "Moga",
        "state": "Punjab",
        "pin_code": "142001",
        "latitude": 30.8165,
        "longitude": 75.1723,
        "contact_phone": "01636-228990",
        "capacity_per_day": 230,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 6.9,
        "workload_pct": 69.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Sangrur Dhuri Road APMC Dana Mandi",
        "code": "APC-PB-SNG-05",
        "address": "Dhuri Road, New Grain Market, Sangrur",
        "district": "Sangrur",
        "state": "Punjab",
        "pin_code": "148001",
        "latitude": 30.2452,
        "longitude": 75.8421,
        "contact_phone": "01672-234112",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.0,
        "workload_pct": 68.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Patiala Sirhind Road APMC Yard",
        "code": "APC-PB-PTL-06",
        "address": "Sirhind Road, New Grain Market, Patiala",
        "district": "Patiala",
        "state": "Punjab",
        "pin_code": "147001",
        "latitude": 30.3412,
        "longitude": 76.3982,
        "contact_phone": "0175-2210889",
        "capacity_per_day": 210,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.1,
        "workload_pct": 65.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Kotkapura Cotton & Grain Market",
        "code": "APC-PB-KKP-07",
        "address": "Faridkot Road, Grain Market, Kotkapura",
        "district": "Faridkot",
        "state": "Punjab",
        "pin_code": "151204",
        "latitude": 30.5821,
        "longitude": 74.8214,
        "contact_phone": "01635-220456",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.2,
        "workload_pct": 64.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Jalandhar Maqsudan Grain Market",
        "code": "APC-PB-JAL-08",
        "address": "GT Road, Maqsudan Mandi, Jalandhar",
        "district": "Jalandhar",
        "state": "Punjab",
        "pin_code": "144008",
        "latitude": 31.3542,
        "longitude": 75.5682,
        "contact_phone": "0181-2270991",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.0,
        "workload_pct": 67.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Amritsar Bhagtanwala Grain Market",
        "code": "APC-PB-ASR-09",
        "address": "Bhagtanwala, Gate Hakima Road, Amritsar",
        "district": "Amritsar",
        "state": "Punjab",
        "pin_code": "143001",
        "latitude": 31.6124,
        "longitude": 74.8712,
        "contact_phone": "0183-2541229",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 6.8,
        "workload_pct": 70.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Kapurthala Subhanpur Road APMC Yard",
        "code": "APC-PB-KPR-10",
        "address": "Subhanpur Road, New Grain Market, Kapurthala",
        "district": "Kapurthala",
        "state": "Punjab",
        "pin_code": "144601",
        "latitude": 31.3812,
        "longitude": 75.3852,
        "contact_phone": "01822-232114",
        "capacity_per_day": 180,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.4,
        "workload_pct": 62.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },

    # 5. Rajasthan
    {
        "name": "Jaipur Krishi Upaj Mandi Samiti (Muhana)",
        "code": "APC-RJ-JPR-01",
        "address": "Muhana Mandi Terminal Market, Sanganer, Jaipur",
        "district": "Jaipur",
        "state": "Rajasthan",
        "pin_code": "302029",
        "latitude": 26.8124,
        "longitude": 75.7683,
        "contact_phone": "0141-2771234",
        "capacity_per_day": 300,
        "active_counters": 8,
        "total_counters": 11,
        "avg_processing_time_min": 7.0,
        "workload_pct": 72.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Kota Bhamashah Krishi Upaj Mandi",
        "code": "APC-RJ-KTA-02",
        "address": "Anantpura, Bhamashah Mandi Complex, Kota",
        "district": "Kota",
        "state": "Rajasthan",
        "pin_code": "324005",
        "latitude": 25.1382,
        "longitude": 75.8456,
        "contact_phone": "0744-2490567",
        "capacity_per_day": 260,
        "active_counters": 7,
        "total_counters": 9,
        "avg_processing_time_min": 7.2,
        "workload_pct": 70.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Sri Ganganagar New Dhan Mandi (APMC)",
        "code": "APC-RJ-SGN-03",
        "address": "Suratgarh Road, New Dhan Mandi, Sri Ganganagar",
        "district": "Sri Ganganagar",
        "state": "Rajasthan",
        "pin_code": "335001",
        "latitude": 29.9142,
        "longitude": 73.8821,
        "contact_phone": "0154-2440890",
        "capacity_per_day": 250,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.0,
        "workload_pct": 68.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Alwar Krishi Upaj Mandi Samiti (Khedli Phatak)",
        "code": "APC-RJ-ALW-04",
        "address": "Delhi Road, Khedli Phatak, Alwar",
        "district": "Alwar",
        "state": "Rajasthan",
        "pin_code": "301001",
        "latitude": 27.5682,
        "longitude": 76.6124,
        "contact_phone": "0144-2331456",
        "capacity_per_day": 180,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.8,
        "workload_pct": 61.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Bharatpur Kumher Gate Krishi Mandi",
        "code": "APC-RJ-BHP-05",
        "address": "Kumher Gate, Mandi Yard, Bharatpur",
        "district": "Bharatpur",
        "state": "Rajasthan",
        "pin_code": "321001",
        "latitude": 27.2152,
        "longitude": 77.4921,
        "contact_phone": "05644-224119",
        "capacity_per_day": 160,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 8.0,
        "workload_pct": 59.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Bikaner Krishi Upaj Mandi (Grain Market)",
        "code": "APC-RJ-BKN-06",
        "address": "Nokha Road, Gangashahar, Bikaner",
        "district": "Bikaner",
        "state": "Rajasthan",
        "pin_code": "334001",
        "latitude": 28.0182,
        "longitude": 73.3124,
        "contact_phone": "0151-2201992",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.5,
        "workload_pct": 65.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Hanumangarh Town Dhan Mandi",
        "code": "APC-RJ-HNM-07",
        "address": "Abohar Road, New Dhan Mandi, Hanumangarh Town",
        "district": "Hanumangarh",
        "state": "Rajasthan",
        "pin_code": "335513",
        "latitude": 29.5812,
        "longitude": 74.3282,
        "contact_phone": "01552-222415",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.1,
        "workload_pct": 66.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Jodhpur Basni Krishi Upaj Mandi",
        "code": "APC-RJ-JDH-08",
        "address": "Basni Phase 2, Industrial Area, Jodhpur",
        "district": "Jodhpur",
        "state": "Rajasthan",
        "pin_code": "342005",
        "latitude": 26.2412,
        "longitude": 73.0182,
        "contact_phone": "0291-2740981",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.4,
        "workload_pct": 67.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },

    # 6. Madhya Pradesh
    {
        "name": "Indore Choithram APMC Mandi",
        "code": "APC-MP-IDR-01",
        "address": "Manik Bagh Road, Choithram Mandi Parisar, Indore",
        "district": "Indore",
        "state": "Madhya Pradesh",
        "pin_code": "452014",
        "latitude": 22.6842,
        "longitude": 75.8492,
        "contact_phone": "0731-2489012",
        "capacity_per_day": 320,
        "active_counters": 8,
        "total_counters": 12,
        "avg_processing_time_min": 6.8,
        "workload_pct": 78.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Bhopal Karond Krishi Upaj Mandi",
        "code": "APC-MP-BPL-02",
        "address": "Karond By-Pass, Mandi Road, Bhopal",
        "district": "Bhopal",
        "state": "Madhya Pradesh",
        "pin_code": "462038",
        "latitude": 23.2982,
        "longitude": 77.4124,
        "contact_phone": "0755-2741990",
        "capacity_per_day": 250,
        "active_counters": 6,
        "total_counters": 9,
        "avg_processing_time_min": 7.2,
        "workload_pct": 71.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Ujjain Madhav Nagar Krishi Mandi",
        "code": "APC-MP-UJN-03",
        "address": "Maksi Road, Madhav Nagar, Ujjain",
        "district": "Ujjain",
        "state": "Madhya Pradesh",
        "pin_code": "456010",
        "latitude": 23.1824,
        "longitude": 75.7912,
        "contact_phone": "0734-2550123",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.0,
        "workload_pct": 69.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Dewas Krishi Upaj Mandi Samiti (Bhopal Road)",
        "code": "APC-MP-DWS-04",
        "address": "Bhopal Bypass Road, Mandi Parisar, Dewas",
        "district": "Dewas",
        "state": "Madhya Pradesh",
        "pin_code": "455001",
        "latitude": 22.9642,
        "longitude": 76.0592,
        "contact_phone": "07272-251456",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.3,
        "workload_pct": 65.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Jabalpur Krishi Upaj Mandi (Vijay Nagar)",
        "code": "APC-MP-JBP-05",
        "address": "Damoh Road, Near ISBT, Krishi Mandi, Jabalpur",
        "district": "Jabalpur",
        "state": "Madhya Pradesh",
        "pin_code": "482002",
        "latitude": 23.1982,
        "longitude": 79.9242,
        "contact_phone": "0761-2640891",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.5,
        "workload_pct": 66.0,
        "open_time": "08:00 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Gwalior Lashkar Krishi Mandi Samiti",
        "code": "APC-MP-GWL-06",
        "address": "Shivpuri Link Road, Lashkar, Gwalior",
        "district": "Gwalior",
        "state": "Madhya Pradesh",
        "pin_code": "474009",
        "latitude": 26.2082,
        "longitude": 78.1562,
        "contact_phone": "0751-2430112",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.6,
        "workload_pct": 63.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Sehore Krishi Upaj Mandi (Sharbati Wheat Hub)",
        "code": "APC-MP-SHR-07",
        "address": "Bhopal-Indore Highway, Mandi Parisar, Sehore",
        "district": "Sehore",
        "state": "Madhya Pradesh",
        "pin_code": "466001",
        "latitude": 23.2012,
        "longitude": 77.0852,
        "contact_phone": "07562-224551",
        "capacity_per_day": 260,
        "active_counters": 7,
        "total_counters": 9,
        "avg_processing_time_min": 6.9,
        "workload_pct": 74.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Vidisha Krishi Upaj Mandi Samiti",
        "code": "APC-MP-VDS-08",
        "address": "Sanchi Road, Mandi Parisar, Vidisha",
        "district": "Vidisha",
        "state": "Madhya Pradesh",
        "pin_code": "464001",
        "latitude": 23.5282,
        "longitude": 77.8124,
        "contact_phone": "07592-232119",
        "capacity_per_day": 230,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.1,
        "workload_pct": 69.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Mandsaur Krishi Upaj Mandi (Garlic & Grain Hub)",
        "code": "APC-MP-MDS-09",
        "address": "Neemuch Road, Krishi Upaj Mandi, Mandsaur",
        "district": "Mandsaur",
        "state": "Madhya Pradesh",
        "pin_code": "458001",
        "latitude": 24.0712,
        "longitude": 75.0742,
        "contact_phone": "07422-242099",
        "capacity_per_day": 250,
        "active_counters": 6,
        "total_counters": 9,
        "avg_processing_time_min": 7.0,
        "workload_pct": 72.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Narmadapuram (Hoshangabad) Itarsi Road Mandi",
        "code": "APC-MP-HSH-10",
        "address": "Itarsi Road, Krishi Upaj Mandi, Narmadapuram",
        "district": "Narmadapuram",
        "state": "Madhya Pradesh",
        "pin_code": "461001",
        "latitude": 22.7482,
        "longitude": 77.7282,
        "contact_phone": "07574-252110",
        "capacity_per_day": 210,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.3,
        "workload_pct": 66.0,
        "open_time": "08:00 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },

    # 7. Maharashtra
    {
        "name": "Lasalgaon APMC Market Yard (Nashik)",
        "code": "APC-MH-LSG-01",
        "address": "Vinchur Road, Lasalgaon APMC Yard, Niphad, Nashik",
        "district": "Nashik",
        "state": "Maharashtra",
        "pin_code": "422306",
        "latitude": 20.1472,
        "longitude": 74.2274,
        "contact_phone": "02550-266123",
        "capacity_per_day": 350,
        "active_counters": 9,
        "total_counters": 12,
        "avg_processing_time_min": 6.5,
        "workload_pct": 80.0,
        "open_time": "06:30 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Pune Gultekdi Agricultural APMC Yard",
        "code": "APC-MH-PUN-02",
        "address": "Market Yard, Gultekdi, Swargate, Pune",
        "district": "Pune",
        "state": "Maharashtra",
        "pin_code": "411037",
        "latitude": 18.4892,
        "longitude": 73.8645,
        "contact_phone": "020-24267890",
        "capacity_per_day": 300,
        "active_counters": 8,
        "total_counters": 11,
        "avg_processing_time_min": 6.8,
        "workload_pct": 76.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Vashi APMC Grain & Produce Terminal (Navi Mumbai)",
        "code": "APC-MH-VSH-03",
        "address": "Sector 19, APMC Market-1, Turbhe, Vashi, Navi Mumbai",
        "district": "Thane",
        "state": "Maharashtra",
        "pin_code": "400703",
        "latitude": 19.0728,
        "longitude": 73.0042,
        "contact_phone": "022-27881234",
        "capacity_per_day": 320,
        "active_counters": 8,
        "total_counters": 12,
        "avg_processing_time_min": 7.0,
        "workload_pct": 77.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Nagpur Kalamna Grain APMC Market",
        "code": "APC-MH-NGP-04",
        "address": "Kalamna Market Yard, Kamptee Road, Nagpur",
        "district": "Nagpur",
        "state": "Maharashtra",
        "pin_code": "440026",
        "latitude": 21.1824,
        "longitude": 79.1356,
        "contact_phone": "0712-2680456",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.2,
        "workload_pct": 69.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Jalgaon New Grain APMC Market Yard",
        "code": "APC-MH-JLG-05",
        "address": "NH-6, Near MIDC, New Market Yard, Jalgaon",
        "district": "Jalgaon",
        "state": "Maharashtra",
        "pin_code": "425003",
        "latitude": 21.0182,
        "longitude": 75.5682,
        "contact_phone": "0257-2210881",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.4,
        "workload_pct": 66.0,
        "open_time": "08:00 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Ahmednagar New Market Yard (APMC)",
        "code": "APC-MH-AHM-06",
        "address": "Kalyan Road, Near Kedgaon, Ahmednagar",
        "district": "Ahmednagar",
        "state": "Maharashtra",
        "pin_code": "414005",
        "latitude": 19.0882,
        "longitude": 74.7252,
        "contact_phone": "0241-2450119",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.5,
        "workload_pct": 64.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Kolhapur Shahu Market Yard (APMC)",
        "code": "APC-MH-KLP-07",
        "address": "Shahu Market Yard, Temblaiwadi, Kolhapur",
        "district": "Kolhapur",
        "state": "Maharashtra",
        "pin_code": "416005",
        "latitude": 16.6982,
        "longitude": 74.2482,
        "contact_phone": "0231-2601229",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.3,
        "workload_pct": 67.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Solapur Siddheshwar Krishi APMC Mandi",
        "code": "APC-MH-SLP-08",
        "address": "Hotgi Road, Near Railway Lines, Solapur",
        "district": "Solapur",
        "state": "Maharashtra",
        "pin_code": "413003",
        "latitude": 17.6582,
        "longitude": 75.9082,
        "contact_phone": "0217-2310451",
        "capacity_per_day": 210,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.4,
        "workload_pct": 65.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },

    # 8. Gujarat
    {
        "name": "Unjha APMC Yard (Asia's Largest Spice & Cumin Hub)",
        "code": "APC-GJ-UNJ-01",
        "address": "Patan Road, APMC Market Yard, Unjha, Mehsana",
        "district": "Mehsana",
        "state": "Gujarat",
        "pin_code": "384170",
        "latitude": 23.8052,
        "longitude": 72.3912,
        "contact_phone": "02767-252345",
        "capacity_per_day": 340,
        "active_counters": 9,
        "total_counters": 12,
        "avg_processing_time_min": 6.6,
        "workload_pct": 79.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Gondal APMC Market Yard (Saurashtra Hub)",
        "code": "APC-GJ-GDL-02",
        "address": "National Highway 27, Marketing Yard, Gondal, Rajkot",
        "district": "Rajkot",
        "state": "Gujarat",
        "pin_code": "360311",
        "latitude": 21.9612,
        "longitude": 70.7982,
        "contact_phone": "02825-220123",
        "capacity_per_day": 300,
        "active_counters": 8,
        "total_counters": 11,
        "avg_processing_time_min": 6.7,
        "workload_pct": 75.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Rajkot Bedipara APMC Grain & Cotton Yard",
        "code": "APC-GJ-RJK-03",
        "address": "Bedipara, Dudhsagar Road, Rajkot",
        "district": "Rajkot",
        "state": "Gujarat",
        "pin_code": "360003",
        "latitude": 22.3112,
        "longitude": 70.8124,
        "contact_phone": "0281-2445678",
        "capacity_per_day": 260,
        "active_counters": 7,
        "total_counters": 9,
        "avg_processing_time_min": 7.0,
        "workload_pct": 71.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Surat APMC Sahara Darwaja Produce Yard",
        "code": "APC-GJ-SRT-04",
        "address": "Sahara Darwaja, Ring Road, Surat",
        "district": "Surat",
        "state": "Gujarat",
        "pin_code": "395002",
        "latitude": 21.1982,
        "longitude": 72.8412,
        "contact_phone": "0261-2321456",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.2,
        "workload_pct": 68.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Deesa APMC Yard (Potato & Mustard Hub)",
        "code": "APC-GJ-DSA-05",
        "address": "Tharad Road, APMC Market Yard, Deesa, Banaskantha",
        "district": "Banaskantha",
        "state": "Gujarat",
        "pin_code": "385535",
        "latitude": 24.2582,
        "longitude": 72.1812,
        "contact_phone": "02744-220881",
        "capacity_per_day": 280,
        "active_counters": 7,
        "total_counters": 9,
        "avg_processing_time_min": 6.9,
        "workload_pct": 73.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Ahmedabad Jamalpur & Naroda APMC Yard",
        "code": "APC-GJ-AMD-06",
        "address": "Naroda Dehgam Road, APMC Yard, Ahmedabad",
        "district": "Ahmedabad",
        "state": "Gujarat",
        "pin_code": "382330",
        "latitude": 23.0782,
        "longitude": 72.6482,
        "contact_phone": "079-22810992",
        "capacity_per_day": 280,
        "active_counters": 7,
        "total_counters": 10,
        "avg_processing_time_min": 7.0,
        "workload_pct": 72.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },

    # 9. Bihar
    {
        "name": "Gulabbagh APMC Yard (Eastern India Maize Hub)",
        "code": "APC-BR-PUR-01",
        "address": "NH-31, Gulabbagh Mandi, Purnea",
        "district": "Purnea",
        "state": "Bihar",
        "pin_code": "854326",
        "latitude": 25.7782,
        "longitude": 87.5142,
        "contact_phone": "06454-242123",
        "capacity_per_day": 300,
        "active_counters": 8,
        "total_counters": 11,
        "avg_processing_time_min": 6.8,
        "workload_pct": 77.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Muzaffarpur Bairia APMC Market Yard",
        "code": "APC-BR-MZF-02",
        "address": "Bairia Bus Stand Road, Mandi Parisar, Muzaffarpur",
        "district": "Muzaffarpur",
        "state": "Bihar",
        "pin_code": "842003",
        "latitude": 26.1342,
        "longitude": 85.3682,
        "contact_phone": "0621-2245678",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.4,
        "workload_pct": 68.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Patna Mithapur Krishi Bazar Samiti Yard",
        "code": "APC-BR-PAT-03",
        "address": "Mithapur Farm Area, Bazar Samiti, Patna",
        "district": "Patna",
        "state": "Bihar",
        "pin_code": "800001",
        "latitude": 25.5941,
        "longitude": 85.1376,
        "contact_phone": "0612-2223456",
        "capacity_per_day": 250,
        "active_counters": 6,
        "total_counters": 9,
        "avg_processing_time_min": 7.1,
        "workload_pct": 72.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Bhagalpur Barari Krishi Bazar Samiti",
        "code": "APC-BR-BHG-04",
        "address": "Barari Industrial Area, Bazar Samiti, Bhagalpur",
        "district": "Bhagalpur",
        "state": "Bihar",
        "pin_code": "812003",
        "latitude": 25.2425,
        "longitude": 87.0214,
        "contact_phone": "0641-2401889",
        "capacity_per_day": 180,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.6,
        "workload_pct": 64.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Begusarai Harrakh Bazar Samiti Yard",
        "code": "APC-BR-BGS-05",
        "address": "Harrakh, Near Railway Station, Begusarai",
        "district": "Begusarai",
        "state": "Bihar",
        "pin_code": "851101",
        "latitude": 25.4182,
        "longitude": 86.1342,
        "contact_phone": "06243-222119",
        "capacity_per_day": 190,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.3,
        "workload_pct": 65.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },

    # 10. West Bengal
    {
        "name": "Siliguri Regulated Market (North Bengal Hub)",
        "code": "APC-WB-SLG-01",
        "address": "Champasari, Regulated Market Complex, Siliguri, Darjeeling",
        "district": "Darjeeling",
        "state": "West Bengal",
        "pin_code": "734003",
        "latitude": 26.7412,
        "longitude": 88.4214,
        "contact_phone": "0353-2512345",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.2,
        "workload_pct": 71.0,
        "open_time": "07:00 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Burdwan (Purba Bardhaman) Grain Mandi",
        "code": "APC-WB-BDN-02",
        "address": "Alisha, GT Road, Bardhaman Regulated Market, Purba Bardhaman",
        "district": "Purba Bardhaman",
        "state": "West Bengal",
        "pin_code": "713103",
        "latitude": 23.2324,
        "longitude": 87.8615,
        "contact_phone": "0342-2645678",
        "capacity_per_day": 260,
        "active_counters": 6,
        "total_counters": 9,
        "avg_processing_time_min": 7.0,
        "workload_pct": 73.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Nadia Bethuadahari Regulated Market",
        "code": "APC-WB-NDA-03",
        "address": "NH-34, Bethuadahari, Nakashipara, Nadia",
        "district": "Nadia",
        "state": "West Bengal",
        "pin_code": "741126",
        "latitude": 23.6124,
        "longitude": 88.3842,
        "contact_phone": "03474-255123",
        "capacity_per_day": 180,
        "active_counters": 4,
        "total_counters": 6,
        "avg_processing_time_min": 7.5,
        "workload_pct": 63.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Malda English Bazar Regulated Market",
        "code": "APC-WB-MLD-04",
        "address": "NH-34, Mokdumpur, English Bazar, Malda",
        "district": "Malda",
        "state": "West Bengal",
        "pin_code": "732101",
        "latitude": 25.0112,
        "longitude": 88.1412,
        "contact_phone": "03512-252089",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.3,
        "workload_pct": 66.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },

    # 11. Andhra Pradesh & Telangana
    {
        "name": "Guntur Mirchi & Grain APMC Yard (Asia's Chilli Hub)",
        "code": "APC-AP-GNT-01",
        "address": "Chilakaluripet Road, Agricultural Market Yard, Guntur",
        "district": "Guntur",
        "state": "Andhra Pradesh",
        "pin_code": "522004",
        "latitude": 16.2912,
        "longitude": 80.4356,
        "contact_phone": "0863-2234567",
        "capacity_per_day": 350,
        "active_counters": 9,
        "total_counters": 13,
        "avg_processing_time_min": 6.5,
        "workload_pct": 81.0,
        "open_time": "06:30 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Warangal Enmamula Grain Market Yard (Telangana)",
        "code": "APC-TG-WGL-02",
        "address": "Enmamula Market Yard, Hunter Road, Warangal",
        "district": "Warangal",
        "state": "Telangana",
        "pin_code": "506005",
        "latitude": 17.9812,
        "longitude": 79.6124,
        "contact_phone": "0870-2441234",
        "capacity_per_day": 320,
        "active_counters": 8,
        "total_counters": 12,
        "avg_processing_time_min": 6.7,
        "workload_pct": 78.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Nizamabad Agricultural Market Yard (Turmeric Hub)",
        "code": "APC-TG-NZB-03",
        "address": "Bodhan Road, Agriculture Market Yard, Nizamabad",
        "district": "Nizamabad",
        "state": "Telangana",
        "pin_code": "503001",
        "latitude": 18.6712,
        "longitude": 78.0982,
        "contact_phone": "08462-231123",
        "capacity_per_day": 260,
        "active_counters": 7,
        "total_counters": 9,
        "avg_processing_time_min": 7.0,
        "workload_pct": 72.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Khammam Grain & Chilli Market Yard",
        "code": "APC-TG-KHM-04",
        "address": "Wyra Road, Agricultural Market Yard, Khammam",
        "district": "Khammam",
        "state": "Telangana",
        "pin_code": "507001",
        "latitude": 17.2472,
        "longitude": 80.1512,
        "contact_phone": "08742-224119",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.1,
        "workload_pct": 70.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Kurnool Agricultural APMC Market Yard",
        "code": "APC-AP-KRN-05",
        "address": "Bellary Road, Agricultural Market Committee, Kurnool",
        "district": "Kurnool",
        "state": "Andhra Pradesh",
        "pin_code": "518003",
        "latitude": 15.8282,
        "longitude": 78.0342,
        "contact_phone": "08518-230981",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.3,
        "workload_pct": 68.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },

    # 12. Karnataka
    {
        "name": "Hubli Amargol APMC Market Yard (North Karnataka Hub)",
        "code": "APC-KA-HBL-01",
        "address": "Amargol, PB Road, APMC Market Yard, Hubli, Dharwad",
        "district": "Dharwad",
        "state": "Karnataka",
        "pin_code": "580025",
        "latitude": 15.3912,
        "longitude": 75.1082,
        "contact_phone": "0836-2223456",
        "capacity_per_day": 300,
        "active_counters": 8,
        "total_counters": 11,
        "avg_processing_time_min": 6.8,
        "workload_pct": 76.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Davanagere APMC Market Yard",
        "code": "APC-KA-DVG-02",
        "address": "Hadadi Road, APMC Yard, Davanagere",
        "district": "Davanagere",
        "state": "Karnataka",
        "pin_code": "577005",
        "latitude": 14.4642,
        "longitude": 75.9214,
        "contact_phone": "08192-231190",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.1,
        "workload_pct": 70.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Shivamogga (Shimoga) APMC Grain Yard",
        "code": "APC-KA-SHM-03",
        "address": "Sagar Road, APMC Yard, Shivamogga",
        "district": "Shivamogga",
        "state": "Karnataka",
        "pin_code": "577204",
        "latitude": 13.9312,
        "longitude": 75.5682,
        "contact_phone": "08182-224567",
        "capacity_per_day": 200,
        "active_counters": 5,
        "total_counters": 7,
        "avg_processing_time_min": 7.4,
        "workload_pct": 65.0,
        "open_time": "08:00 AM",
        "close_time": "06:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Ballari (Bellary) APMC Market Yard",
        "code": "APC-KA-BLR-04",
        "address": "Anantapur Road, APMC Market Yard, Ballari",
        "district": "Ballari",
        "state": "Karnataka",
        "pin_code": "583101",
        "latitude": 15.1412,
        "longitude": 76.9214,
        "contact_phone": "08392-270889",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.3,
        "workload_pct": 67.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Raichur Cotton & Grain APMC Yard",
        "code": "APC-KA-RCH-05",
        "address": "Hyderabad Road, APMC Market Yard, Raichur",
        "district": "Raichur",
        "state": "Karnataka",
        "pin_code": "584102",
        "latitude": 16.2082,
        "longitude": 77.3582,
        "contact_phone": "08532-232115",
        "capacity_per_day": 240,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.2,
        "workload_pct": 71.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },

    # 13. Tamil Nadu, Odisha & Chhattisgarh
    {
        "name": "Madurai Central Agricultural Market Committee Yard",
        "code": "APC-TN-MDU-01",
        "address": "Mattuthavani, Regulated Market Committee, Madurai",
        "district": "Madurai",
        "state": "Tamil Nadu",
        "pin_code": "625007",
        "latitude": 9.9482,
        "longitude": 78.1562,
        "contact_phone": "0452-2580123",
        "capacity_per_day": 250,
        "active_counters": 6,
        "total_counters": 8,
        "avg_processing_time_min": 7.2,
        "workload_pct": 70.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Thanjavur Delta Paddy Procurement Yard",
        "code": "APC-TN-TNJ-02",
        "address": "Trichy Main Road, Regulated Market Committee, Thanjavur",
        "district": "Thanjavur",
        "state": "Tamil Nadu",
        "pin_code": "613007",
        "latitude": 10.7870,
        "longitude": 79.1378,
        "contact_phone": "04362-274567",
        "capacity_per_day": 280,
        "active_counters": 7,
        "total_counters": 10,
        "avg_processing_time_min": 6.9,
        "workload_pct": 76.0,
        "open_time": "06:30 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Bargarh Regulated Market Committee (Odisha Rice Bowl)",
        "code": "APC-OD-BGR-01",
        "address": "Bhatli Road, RMC Market Yard, Bargarh",
        "district": "Bargarh",
        "state": "Odisha",
        "pin_code": "768028",
        "latitude": 21.3324,
        "longitude": 83.6215,
        "contact_phone": "06646-234567",
        "capacity_per_day": 260,
        "active_counters": 6,
        "total_counters": 9,
        "avg_processing_time_min": 7.0,
        "workload_pct": 73.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Sambalpur Khetrajpur RMC Grain Yard",
        "code": "APC-OD-SBP-02",
        "address": "Khetrajpur, Regulated Market Committee, Sambalpur",
        "district": "Sambalpur",
        "state": "Odisha",
        "pin_code": "768003",
        "latitude": 21.4882,
        "longitude": 83.9782,
        "contact_phone": "0663-2540112",
        "capacity_per_day": 220,
        "active_counters": 5,
        "total_counters": 8,
        "avg_processing_time_min": 7.2,
        "workload_pct": 69.0,
        "open_time": "07:30 AM",
        "close_time": "06:30 PM",
        "status": CentreStatus.OPEN,
    },
    {
        "name": "Raipur Krishi Upaj Mandi Samiti (Pandri / Dumartarai)",
        "code": "APC-CG-RPR-01",
        "address": "Dumartarai Mandi Complex, Dhamtari Road, Raipur",
        "district": "Raipur",
        "state": "Chhattisgarh",
        "pin_code": "492015",
        "latitude": 21.2012,
        "longitude": 81.6582,
        "contact_phone": "0771-2440981",
        "capacity_per_day": 280,
        "active_counters": 7,
        "total_counters": 10,
        "avg_processing_time_min": 6.9,
        "workload_pct": 74.0,
        "open_time": "07:00 AM",
        "close_time": "07:00 PM",
        "status": CentreStatus.OPEN,
    },
]

def seed_india_mandis():
    db = SessionLocal()
    try:
        now = datetime.now()
        date_strs = [(now + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(14)]
        slot_times = [
            ("08:00 AM", "09:30 AM"),
            ("09:30 AM", "11:00 AM"),
            ("11:00 AM", "12:30 PM"),
            ("01:30 PM", "03:00 PM"),
            ("03:00 PM", "04:30 PM"),
            ("04:30 PM", "06:00 PM"),
        ]

        total_upserted = 0
        total_slots_created = 0

        for item in INDIA_MANDIS:
            centre = db.query(ProcurementCentre).filter(ProcurementCentre.code == item["code"]).first()
            if not centre:
                # Also check by name
                centre = db.query(ProcurementCentre).filter(ProcurementCentre.name == item["name"]).first()

            if not centre:
                centre = ProcurementCentre(
                    name=item["name"],
                    code=item["code"],
                    address=item["address"],
                    district=item["district"],
                    state=item["state"],
                    pin_code=item["pin_code"],
                    latitude=item["latitude"],
                    longitude=item["longitude"],
                    contact_phone=item["contact_phone"],
                    capacity_per_day=item["capacity_per_day"],
                    active_counters=item["active_counters"],
                    total_counters=item["total_counters"],
                    avg_processing_time_min=item["avg_processing_time_min"],
                    workload_pct=item["workload_pct"],
                    open_time=item["open_time"],
                    close_time=item["close_time"],
                    status=item["status"],
                )
                db.add(centre)
                db.flush()
                total_upserted += 1
            else:
                centre.address = item["address"]
                centre.district = item["district"]
                centre.state = item["state"]
                centre.pin_code = item["pin_code"]
                centre.latitude = item["latitude"]
                centre.longitude = item["longitude"]
                centre.contact_phone = item["contact_phone"]
                centre.capacity_per_day = item["capacity_per_day"]
                centre.active_counters = item["active_counters"]
                centre.total_counters = item["total_counters"]
                centre.avg_processing_time_min = item["avg_processing_time_min"]
                centre.workload_pct = item["workload_pct"]
                centre.open_time = item["open_time"]
                centre.close_time = item["close_time"]
                centre.status = item["status"]
                db.flush()

            # Ensure slots exist for upcoming dates
            for d_str in date_strs:
                existing_slots = db.query(Slot).filter(Slot.centre_id == centre.id, Slot.date == d_str).count()
                if existing_slots == 0:
                    for s_idx, (st, et) in enumerate(slot_times):
                        slot = Slot(
                            centre_id=centre.id,
                            date=d_str,
                            start_time=st,
                            end_time=et,
                            capacity=20,
                            booked_count=0,
                            is_recommended=(s_idx == 1 or s_idx == 2),
                            is_active=True,
                        )
                        db.add(slot)
                        total_slots_created += 1

        db.commit()
        count = db.query(ProcurementCentre).count()
        print(f"[AGRIQUENE SEEDER] Success! Total Mandis in DB: {count} (New/Updated: {total_upserted}, Slots created: {total_slots_created})")
    except Exception as e:
        db.rollback()
        print(f"[AGRIQUENE SEEDER] Error: {e}")
        raise e
    finally:
        db.close()

if __name__ == "__main__":
    seed_india_mandis()
